exclude:
  - docker-compose.yml
# theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
search_enabled: false
aux_links:
  "useResource on GitHub":
    - "//github.com/alexjamesmalcolm/use-resource"
# Footer content
# appears at the bottom of every page's main content
#footer_content: 'Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href="https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt">MIT license.</a>'

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/alexjamesmalcolm/use-resource" # the github URL for your repo
gh_edit_branch: "master/docs" # the branch that your docs is served from
gh_edit_view_mode: "blob" # "tree" or "edit" if you want the user to jump into the editor immediately
