version: "2"

services:
  jekyll:
    image: jekyll/jekyll:4
    command: jekyll serve --config _config.yml,_local_config.yml --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
